const PERMISSIONS = {
  WILDCARD: "*",

  ADMIN_ACCESS: "admin:access",
  ADMIN_MANAGE: "admin:manage",
  PROTECTED_OWNER_ONLY: "protected:owner_only",

  AUDIT_READ_ALL: "audit:read_all",
  AUDIT_READ_OWN: "audit:read_own",

  CAMPUS_READ_ALL: "campus:read_all",
  CAMPUS_READ_OWN: "campus:read_own",
  CAMPUS_CREATE: "campus:create",
  CAMPUS_UPDATE: "campus:update",
  CAMPUS_DELETE: "campus:delete",

  ACADEMIC_LEVEL_READ_ALL: "academic_level:read_all",
  ACADEMIC_LEVEL_READ_OWN: "academic_level:read_own",
  ACADEMIC_LEVEL_CREATE: "academic_level:create",
  ACADEMIC_LEVEL_UPDATE: "academic_level:update",
  ACADEMIC_LEVEL_DELETE: "academic_level:delete",

  STAFF_READ_ALL: "staff:read_all",
  STAFF_READ_OWN: "staff:read_own",
  STAFF_CREATE: "staff:create",
  STAFF_UPDATE: "staff:update",
  STAFF_DELETE: "staff:delete",

  TEACHER_CREATE: "teacher:create",
  TEACHER_READ: "teacher:read",
  TEACHER_UPDATE: "teacher:update",
  TEACHER_DELETE: "teacher:delete",
  TEACHER_SUBJECT_ASSIGN: "teacher_subject:assign",
  TEACHER_AVAILABILITY_SET: "teacher_availability:set",
  TEACHER_AVAILABILITY_SELF: "teacher_availability:self",

  DEPARTMENT_READ: "department:read",
  DEPARTMENT_CREATE: "department:create",
  DEPARTMENT_UPDATE: "department:update",
  DEPARTMENT_DELETE: "department:delete",

  SUBJECT_READ: "subject:read",
  SUBJECT_CREATE: "subject:create",
  SUBJECT_UPDATE: "subject:update",
  SUBJECT_DELETE: "subject:delete",

  TIMESLOT_MANAGE: "timeslot:manage",
  WORKINGDAY_MANAGE: "workingday:manage",

  INVITE_MANAGE: "invite:manage",

  TIMETABLE_READ: "timetable:read",
  TIMETABLE_GENERATE: "timetable:generate",
  TIMETABLE_MANAGE: "timetable:manage",
};

const ADMIN_PERMISSIONS = [
  PERMISSIONS.ADMIN_ACCESS,
  PERMISSIONS.ADMIN_MANAGE,
];

const PROTECTED_PERMISSIONS = [
  PERMISSIONS.PROTECTED_OWNER_ONLY,
];

const AUDIT_PERMISSIONS = [
  PERMISSIONS.AUDIT_READ_ALL,
  PERMISSIONS.AUDIT_READ_OWN,
];

const CAMPUS_PERMISSIONS = [
  PERMISSIONS.CAMPUS_READ_ALL,
  PERMISSIONS.CAMPUS_READ_OWN,
  PERMISSIONS.CAMPUS_CREATE,
  PERMISSIONS.CAMPUS_UPDATE,
  PERMISSIONS.CAMPUS_DELETE,
];

const ACADEMIC_LEVEL_PERMISSIONS = [
  PERMISSIONS.ACADEMIC_LEVEL_READ_ALL,
  PERMISSIONS.ACADEMIC_LEVEL_READ_OWN,
  PERMISSIONS.ACADEMIC_LEVEL_CREATE,
  PERMISSIONS.ACADEMIC_LEVEL_UPDATE,
  PERMISSIONS.ACADEMIC_LEVEL_DELETE,
];

const STAFF_PERMISSIONS = [
  PERMISSIONS.STAFF_READ_ALL,
  PERMISSIONS.STAFF_READ_OWN,
  PERMISSIONS.STAFF_CREATE,
  PERMISSIONS.STAFF_UPDATE,
  PERMISSIONS.STAFF_DELETE,
];

const TEACHER_PERMISSIONS = [
  PERMISSIONS.TEACHER_READ,
  PERMISSIONS.TEACHER_CREATE,
  PERMISSIONS.TEACHER_UPDATE,
  PERMISSIONS.TEACHER_DELETE,
  PERMISSIONS.TEACHER_SUBJECT_ASSIGN,
  PERMISSIONS.TEACHER_AVAILABILITY_SET,
  PERMISSIONS.TEACHER_AVAILABILITY_SELF,
];

const DEPARTMENT_PERMISSIONS = [
  PERMISSIONS.DEPARTMENT_READ,
  PERMISSIONS.DEPARTMENT_CREATE,
  PERMISSIONS.DEPARTMENT_UPDATE,
  PERMISSIONS.DEPARTMENT_DELETE,
];

const SUBJECT_PERMISSIONS = [
  PERMISSIONS.SUBJECT_READ,
  PERMISSIONS.SUBJECT_CREATE,
  PERMISSIONS.SUBJECT_UPDATE,
  PERMISSIONS.SUBJECT_DELETE,
];

const TIMESLOT_PERMISSIONS = [
  PERMISSIONS.TIMESLOT_MANAGE,
];

const WORKINGDAY_PERMISSIONS = [
  PERMISSIONS.WORKINGDAY_MANAGE,
];

const INVITE_PERMISSIONS = [
  PERMISSIONS.INVITE_MANAGE,
];

const TIMETABLE_PERMISSIONS = [
  PERMISSIONS.TIMETABLE_READ,
  PERMISSIONS.TIMETABLE_GENERATE,
  PERMISSIONS.TIMETABLE_MANAGE,
];

const PERMISSION_HIERARCHY = {
  [PERMISSIONS.AUDIT_READ_ALL]: [PERMISSIONS.AUDIT_READ_OWN],
  [PERMISSIONS.CAMPUS_READ_ALL]: [PERMISSIONS.CAMPUS_READ_OWN],
  [PERMISSIONS.ACADEMIC_LEVEL_READ_ALL]: [PERMISSIONS.ACADEMIC_LEVEL_READ_OWN],
  [PERMISSIONS.STAFF_READ_ALL]: [PERMISSIONS.STAFF_READ_OWN],
  [PERMISSIONS.TEACHER_CREATE]: [PERMISSIONS.TEACHER_READ],
  [PERMISSIONS.TEACHER_UPDATE]: [PERMISSIONS.TEACHER_READ],
  [PERMISSIONS.TEACHER_DELETE]: [PERMISSIONS.TEACHER_READ],
  [PERMISSIONS.DEPARTMENT_CREATE]: [PERMISSIONS.DEPARTMENT_READ],
  [PERMISSIONS.DEPARTMENT_UPDATE]: [PERMISSIONS.DEPARTMENT_READ],
  [PERMISSIONS.DEPARTMENT_DELETE]: [PERMISSIONS.DEPARTMENT_READ],
  [PERMISSIONS.SUBJECT_CREATE]: [PERMISSIONS.SUBJECT_READ],
  [PERMISSIONS.SUBJECT_UPDATE]: [PERMISSIONS.SUBJECT_READ],
  [PERMISSIONS.SUBJECT_DELETE]: [PERMISSIONS.SUBJECT_READ],
  [PERMISSIONS.TIMETABLE_GENERATE]: [PERMISSIONS.TIMETABLE_READ],
  [PERMISSIONS.TIMETABLE_MANAGE]: [PERMISSIONS.TIMETABLE_READ],
};

module.exports = {
  PERMISSIONS,
  ADMIN_PERMISSIONS,
  PROTECTED_PERMISSIONS,
  AUDIT_PERMISSIONS,
  CAMPUS_PERMISSIONS,
  ACADEMIC_LEVEL_PERMISSIONS,
  STAFF_PERMISSIONS,
  TEACHER_PERMISSIONS,
  DEPARTMENT_PERMISSIONS,
  SUBJECT_PERMISSIONS,
  TIMESLOT_PERMISSIONS,
  WORKINGDAY_PERMISSIONS,
  INVITE_PERMISSIONS,
  TIMETABLE_PERMISSIONS,
  PERMISSION_HIERARCHY,
};
